CREATE TABLE logs (
  id INT NOT NULL AUTO_INCREMENT,
  date DATETIME NOT NULL,
  method VARCHAR(10) NOT NULL,
  uri VARCHAR(255) NOT NULL,
  ip VARCHAR(15) NOT NULL,
  user_agent VARCHAR(255) NOT NULL,
  result INT NOT NULL,
  response_time INT NOT NULL,
  PRIMARY KEY (id)
) AUTO_INCREMENT=1;